require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "script/**/*"
    - "tmp/**/*"
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
